name: Lanzar ETL (privado)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Rama del repo privado"
        required: false
        default: "dev"

jobs:
  dispatch-start-scrap:
    runs-on: ubuntu-latest
    concurrency:
      group: lanzar-start-scrap-${{ github.ref_name }}
      cancel-in-progress: false

    steps:
      - name: Disparar al repo privado por repository_dispatch (type=start-scrap)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          repository: ofrecimientos-docentes/etl-ofrecimientos-docentes
          event-type: start-scrap
          client-payload: |
            {
              "branch": "${{ github.event.inputs.branch || github.ref_name || 'dev' }}"
            }
