name: Lanzar scrap + transform (dev)

on:
  workflow_dispatch: {}

jobs:
  lanzar:
    runs-on: ubuntu-latest
    steps:
      - name: Disparar repo privado
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }} # PAT con acceso al repo privado
          repository: ofrecimientos-docentes/etl-ofrecimientos-docentes
          event-type: run-scrap-transform
          client-payload: |
            { "branch": "dev" }
