name: Mostrar Ofrecimientos (dev)

on:
  push:
    branches:
      - dev
    paths:
      - "ofrecimientos.csv"

jobs:
  mostrar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo público (dev)
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Mostrar primeros 5 ofrecimientos
        run: |
          pip install polars
          python - <<'EOF'
          import polars as pl
          df = pl.read_csv("ofrecimientos.csv")
          print("Primeros 5 ofrecimientos:")
          print(df.head(5))
          EOF
