name: Mostrar observaciones (dev)

on:
  push:
    branches: [dev]
    paths:
      - "observaciones.csv"
  repository_dispatch:
    types: [observaciones-updated]
  workflow_dispatch: {}

jobs:
  mostrar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo público (dev)
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Mostrar conteo y primeras 5 observaciones
        run: |
          python -m pip install --upgrade pip
          pip install polars
          python - <<'PY'
          import polars as pl
          df = pl.read_csv("observaciones.csv")  # id,observaciones
          print(f"✅ Total de observaciones: {df.height}")
          print("▶ Primeras 5:")
          print(df.head(5))
          PY
