name: Procesar observaciones con Gemini (dev)

on:
  push:
    branches: [dev]
    paths:
      - "data/observaciones.csv"
  repository_dispatch:
    types: [observaciones-updated]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  procesar:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout repo público (dev)
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt

      - name: Cache .venv (restore)
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-

      - name: Create venv & install deps (on cache miss)
        if: steps.cache-venv.outputs.cache-hit != 'true'
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Use venv for subsequent steps
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Ejecutar AI de observaciones (Gemini)
        run: python ai/observaciones.py

      - name: Commit & push data/observaciones_final.csv (si cambió)
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if [ -f "data/observaciones_final.csv" ]; then
            git add data/observaciones_final.csv
            git diff --cached --quiet && echo "No changes to commit" || git commit -m "data/observaciones_final.csv generado (AI)"
            git push origin dev
          else
            echo "No se generó data/observaciones_final.csv" && exit 1
          fi

      - name: Checkout repo privado (dev)
        uses: actions/checkout@v4
        with:
          repository: ofrecimientos-docentes/etl-ofrecimientos-docentes # 👈 privado
          token: ${{ secrets.PRIVATE_REPO_TOKEN }} # 👈 secret en el repo público
          ref: dev
          fetch-depth: 0
          path: repo-privado

      - name: Copiar a data/ai/ofrecimientos_final.csv y commitear (privado)
        working-directory: repo-privado
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          mkdir -p data/ai
          cp ../data/observaciones_final.csv data/ai/ofrecimientos_final.csv

          git add data/ai/ofrecimientos_final.csv
          git commit -m "update data/ai/ofrecimientos_final.csv (dev)" || echo "No changes"
          git push origin dev

      # Opcional: dispara también por repository_dispatch al repo privado
      - name: Disparar workflow privado (repository_dispatch)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          repository: ofrecimientos-docentes/etl-ofrecimientos-docentes
          event-type: ai-observaciones-final
          client-payload: |
            {
              "branch": "dev",
              "path": "data/ai/ofrecimientos_final.csv"
            }
