name: Procesar observaciones con Gemini (main)

on:
  repository_dispatch:
    types: [observaciones-updated]
  workflow_dispatch:

permissions:
  contents: write

env:
  TZ: "America/Argentina/San_Juan"
  PYTHONUTF8: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  procesar:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout (main)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # push en ESTE repo

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Cache .venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: venv-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-

      - name: Create venv & install deps (si no hay cache)
        if: steps.cache-venv.outputs.cache-hit != 'true'
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      # Ejecuta el módulo ai.observaciones.main
      - name: Ejecutar AI (ai.observaciones.main)
        shell: bash
        run: |
          source .venv/bin/activate
          python -m ai.observaciones.main

      # --- COMMIT 1: ESTE REPO (data/observaciones_final.csv) ---
      - name: Commit en este repo (main)
        shell: bash
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          test -f data/observaciones_final.csv || { echo "No generado"; exit 1; }

          git pull --rebase origin main || true
          git add data/observaciones_final.csv

          if git diff --cached --quiet; then
            echo "No changes en este repo"
          else
            git commit -m "update data/observaciones_final.csv (AI)"
            git push origin main
          fi

      # --- COMMIT 2: OTRO REPO (etl-ofrecimientos-docentes -> data/ai/observaciones_final.csv) ---
      - name: Checkout repo etl-ofrecimientos-docentes (main)
        uses: actions/checkout@v4
        with:
          repository: ofrecimientos-docentes/etl-ofrecimientos-docentes
          ref: main
          fetch-depth: 0
          path: etl-repo
          token: ${{ secrets.PRIVATE_REPO_TOKEN }} # push en OTRO repo

      - name: Copiar y commitear en etl-ofrecimientos-docentes
        working-directory: etl-repo
        shell: bash
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE/etl-repo"

          git pull --rebase origin main || true

          mkdir -p data/ai
          cp ../data/observaciones_final.csv data/ai/observaciones_final.csv
          git add data/ai/observaciones_final.csv

          if git diff --cached --quiet; then
            echo "No changes en etl-ofrecimientos-docentes"
          else
            git commit -m "update data/ai/observaciones_final.csv (from procesar observaciones)"
            git push origin main
          fi

      # --- DISPATCH luego del commit en el repo privado ---
      - name: Disparar corrección en repo privado
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          repository: ofrecimientos-docentes/etl-ofrecimientos-docentes
          event-type: ai-observaciones-final
