name: Procesar observaciones con Gemini (main)

on:
  repository_dispatch:
    types: [observaciones-updated]
  workflow_dispatch:

permissions:
  contents: write

env:
  TZ: "America/Argentina/San_Juan"
  PYTHONUTF8: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  procesar:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout (main)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          # Usa el GITHUB_TOKEN por defecto para poder pushear
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Cache .venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: venv-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-

      - name: Create venv & install deps (si no hay cache)
        if: steps.cache-venv.outputs.cache-hit != 'true'
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Ejecutar AI
        shell: bash
        run: |
          source .venv/bin/activate
          python ai/observaciones.py

      - name: Commit observaciones_final.csv (root y ai/)
        shell: bash
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          test -f data/observaciones_final.csv || { echo "No generado"; exit 1; }

          # Copia al path solicitado
          mkdir -p data/ai
          cp -f data/observaciones_final.csv data/ai/observaciones_final.csv

          # Evita non-fast-forward si hubo cambios
          git pull --rebase origin main || true

          # Agrega y commitea ambos
          git add data/observaciones_final.csv data/ai/observaciones_final.csv
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "update observaciones_final.csv (AI) [root & data/ai]"
            git push origin main
          fi

      - name: Disparar corrección en repo privado
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          repository: ofrecimientos-docentes/etl-ofrecimientos-docentes
          event-type: ai-observaciones-final
