name: Procesar observaciones con Gemini (dev)

on:
  push:
    branches: [dev]
    paths:
      - "data/observaciones.csv"
  repository_dispatch:
    types: [observaciones-updated]
  workflow_dispatch: {}

permissions:
  contents: write # para poder commitear el CSV generado

jobs:
  procesar:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout repo público (dev)
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install google-genai polars pydantic

      - name: Ejecutar AI de observaciones (Gemini)
        run: |
          python ai/observaciones.py

      - name: Commit & push data/observaciones_final.csv (si cambió)
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if [ -f "data/observaciones_final.csv" ]; then
            git add data/observaciones_final.csv
            git diff --cached --quiet && echo "No changes to commit" || git commit -m "data/observaciones_final.csv generado (AI)"
            git push origin dev
          else
            echo "No se generó data/observaciones_final.csv" && exit 1
          fi

      - name: Subir artifact (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: observaciones_final
          path: data/observaciones_final.csv
